name: DEPLOY PKMN_ANALYZER

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '18'
            cache: 'npm'

        - name: Install dependencies
          run: npm ci

        - name: Build the project
          env:
              VITE_BACKEND_URL: https://pkmn-analyzer-backend.onrender.com
          run: npm run build

        - name: Deploy to Github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: dist
              publish_branch: gh-pages
              cname: false