name: DEPLOY PKMN_ANALYZER

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY }}

    steps:
        #Checkout repository
        - name: Checkout code
          uses: actions/checkout@v3

        #Setup Node.js
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'

        #Install dependencies
        - name: Install dependencies
          run: npm ci

        #Build the project
        - name: Build the project
          run: npm run build

        #Deploy to Github pages
        - name: Deploy to Github pages
          uses: peaceiris/actions-gh-pages@v3
          env:
              API_KEY: ${{ secrets.VITE_GOOGLE_GEMINI_API_KEY }}
          with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              publish_dir: dist
              publish_branch: gh-pages